# Pytorch Test Youtube Building Models
Notebook for following along with Pytorch model building, using [Pytorch](https://pytorch.org/tutorials/beginner/introyt/modelsyt_tutorial.html) website tutorial. This notebook will be similar to the previous Pytorch Test notebooks, as the [youtube content](https://www.youtube.com/watch?v=OSqIP-mOWOI) covers similiar works.

### Choices for data

<br>

### Libaries and Modules
Importing the necessary libaries and modules for the notebook.

In [10]:
#Import cell
import matplotlib as mpl
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import math
import numpy as np
import pandas as pd
import pickle as pk
import torch
import torchvision

import torch.functional as F

print("Imports complete")

Imports complete


<br>

### Importing data sets
Importing the data for the models.

<b>Import sample data set and corresponding time/geo data</b>

In [2]:
#Importing data sets

print("Data sets successfully imported.")

Data sets successfully imported.


<br>

### Class Definitions
<b>Classes:</b><br>
<ul>
<li>TinyModel - 2 linear lays going from 100 -> 200 -> 10 with a linear activation function
<li>LeNet - image recognition model with 2 convolution layers
<li>LSTMTagger - long short-term memory model for word processing using recurrent layers
</ul>

In [14]:
#Class definition cell

class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        
        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()
        return None
    
    def forward(self, x):
        x = self.lienar1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

    
class LeNet(torch.nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        #1 input image channel (black/white), 6 outputs channels, 5x5 square
        self.conv1 = torch.nn.Conv2d(1, 6, 5) 
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        self.fc1 = torch.nn.Linear(16*6*6, 120)
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)
        return None
    
    def forwad(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(selv.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:] #all dimensions except batch
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
    
class LSTMTagger(torch.nn.Module):
    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim
        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)
        return None

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstem(embeds.view(len(sentence), 1 , -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores
    
    
    
print("Classes defined.")

Classes defined.


<br>

### Calculation functions
<b>Functions:</b><br>
<ul>
<li>
</ul>

In [4]:
#Calculation functions cell


print("Calculation functions defined.")

Calculation functions defined.


<br>

### Plotting functions
<b>Functions:</b>
<ul>
<li> 
</ul>

In [5]:
#Plotting functions Cell


print("Plotting functions defined.")

Plotting functions defined.


<br>

### Main code
Initialising an instance of a `torch.nn.Module` subclass.

In [7]:
tinymodel = TinyModel()
print(f"The model:{tinymodel}")
print(f"\nJust one layer:{tinymodel.linear2}")
print(f"\nModel params:")
for param in tinymodel.parameters():
    print(param)

print("\nLayer params:")
for param in tinymodel.linear2.parameters():
    print(param)

The model:TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)

Just one layer:Linear(in_features=200, out_features=10, bias=True)

Model params:
Parameter containing:
tensor([[-0.0552, -0.0786, -0.0446,  ..., -0.0607, -0.0391,  0.0233],
        [-0.0777, -0.0222,  0.0923,  ...,  0.0257,  0.0189,  0.0485],
        [ 0.0966,  0.0363, -0.0230,  ...,  0.0784, -0.0697, -0.0040],
        ...,
        [ 0.0299,  0.0981, -0.0005,  ..., -0.0413, -0.0044, -0.0009],
        [ 0.0844, -0.0336,  0.0232,  ...,  0.0853,  0.0808, -0.0952],
        [ 0.0367,  0.0942, -0.0383,  ...,  0.0525, -0.0793,  0.0670]],
       requires_grad=True)
Parameter containing:
tensor([-0.0417, -0.0615, -0.0467, -0.0579, -0.0712,  0.0678,  0.0997, -0.0784,
         0.0383,  0.0741,  0.0329, -0.0722,  0.0209,  0.0089, -0.0786,  0.0837,
        -0.0922,  0.0249,  0.0810,  0.0646, 

#### Common Layer Types
<ul>
<li>Linear layers - also known as a fully connected layeer. this layer has every input influence every output based on the respective weights. For an m input and n output model, the weights matrix is m x n.</li>
<li>Convolutional layers - these are built to handle data with a high degree of spatial correlation, such as computer vision and NLP applications, where a word's immediate context can affect the meaning of a sentance.</li>
<li>Recurrent Layers - recurrent neural networks (RNNs) are used for sequential data such as time-series measurements. They work by maintaining a hiddenstate that acts as a sort of memory for what it has seen in the sequence so far.</li>
<li>Transformers - these are a more complex type of layer
</ul>

In [9]:
#Linear layers
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print(f"Input: {x}")

print("\nWeight and Bias parameters:")
for param in lin.parameters():
    print(param)
    
y = lin(x)
print(f"\nOutput: {y}")

Input: tensor([[0.7968, 0.8706, 0.5710]])

Weight and Bias parameters:
Parameter containing:
tensor([[ 0.1654, -0.4039,  0.1620],
        [ 0.5345, -0.3973, -0.2266]], requires_grad=True)
Parameter containing:
tensor([0.4379, 0.2286], requires_grad=True)

Output: tensor([[0.3106, 0.1793]], grad_fn=<AddmmBackward0>)


In [13]:
#Convolution layers
convModel = LeNet()

print("Model parameters:")
for param in convModel.parameters():
    print(param)

Model parameters:
Parameter containing:
tensor([[[[ 0.0171,  0.0224,  0.1948,  0.1984,  0.0823],
          [-0.1093, -0.0469, -0.1999,  0.0410,  0.0137],
          [-0.0785, -0.0203,  0.0243, -0.0525, -0.0087],
          [ 0.0360, -0.0256, -0.0685,  0.1159,  0.0426],
          [ 0.0010,  0.0619,  0.1864,  0.0579, -0.1514]]],


        [[[ 0.0651,  0.0926, -0.1308, -0.1586,  0.1469],
          [ 0.0486,  0.0513,  0.1415, -0.0321, -0.1448],
          [-0.0892,  0.0525,  0.1250,  0.1768, -0.0149],
          [-0.1085,  0.1602, -0.0180,  0.0310,  0.0534],
          [-0.0918,  0.0100, -0.0685, -0.0293,  0.1387]]],


        [[[ 0.0823, -0.0320,  0.1378,  0.1303,  0.1434],
          [-0.1019,  0.0417, -0.0984, -0.0530,  0.0240],
          [ 0.0150,  0.0175,  0.0609, -0.0075, -0.1276],
          [ 0.0712, -0.1813, -0.1507,  0.1609, -0.1386],
          [ 0.1789,  0.0161, -0.1002, -0.0076, -0.1455]]],


        [[[ 0.0369,  0.1999,  0.1115,  0.0891,  0.0826],
          [-0.1805,  0.0356, -0.1282

In [17]:
#Recurrent Layers
wordModel = LSTMTagger(3, 3, 2, 3)

print("Model parameters:")
for param in wordModel.parameters():
    print(param)

Model parameters:
Parameter containing:
tensor([[ 0.5741,  0.3693,  0.8634],
        [-0.2332, -0.0196,  0.6296]], requires_grad=True)
Parameter containing:
tensor([[-0.1447,  0.1023, -0.3762],
        [-0.5381, -0.1101, -0.3813],
        [-0.3292,  0.3898,  0.2038],
        [ 0.5135,  0.3544,  0.1592],
        [ 0.1655,  0.0577, -0.2453],
        [-0.5158, -0.4142,  0.3248],
        [ 0.3541,  0.1623, -0.0887],
        [-0.2154,  0.3917,  0.1910],
        [ 0.3112, -0.3907,  0.4102],
        [-0.0568,  0.1463, -0.4533],
        [ 0.4507,  0.1243,  0.0068],
        [-0.4801,  0.5645,  0.2467]], requires_grad=True)
Parameter containing:
tensor([[-0.5500, -0.0385, -0.2593],
        [ 0.3287,  0.3100,  0.0618],
        [-0.1390,  0.4858, -0.2260],
        [-0.2179,  0.2082,  0.1339],
        [-0.4665,  0.2158, -0.3703],
        [-0.1485, -0.4517,  0.2078],
        [-0.1930,  0.2445,  0.3635],
        [ 0.1131, -0.0528,  0.5239],
        [ 0.0540, -0.0454, -0.1256],
        [-0.3769,  0.28

<br>