# Pytorch Test Youtube Tensors Deeper Look
Notebook for following along with the Pytorch tensor deeper look, using [Pytorch](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html) website tutorial. This notebook will be similar to the previous Pytorch Test notebooks, as the [youtube content](https://www.youtube.com/watch?v=r7QDUPb2dCM) covers similiar works.

### Choices for data

<br>

### Libaries and Modules
Importing the necessary libaries and modules for the notebook.

In [1]:
#Import cell
import matplotlib as mpl
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import math
import numpy as np
import pandas as pd
import pickle as pk
import torch
import torchvision



print("Imports complete")

Imports complete


<br>

### Importing data sets
Importing the data for the models.

<b>Import sample data set and corresponding time/geo data</b>

In [2]:
#Importing data sets

print("Data sets successfully imported.")

Data sets successfully imported.


<br>

### Class Definitions
<b>Classes:</b><br>
<ul>
<li>
</ul>

In [3]:
#Class definition cell

print("Classes defined.")

Classes defined.


<br>

### Calculation functions
<b>Functions:</b><br>
<ul>
<li>
</ul>

In [4]:
#Calculation functions cell


print("Calculation functions defined.")

Calculation functions defined.


<br>

### Plotting functions
<b>Functions:</b>
<ul>
<li> 
</ul>

In [5]:
#Plotting functions Cell


print("Plotting functions defined.")

Plotting functions defined.


<br>

### Main code

#### Creating Tensors

In [6]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [8]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


#### Tensor Shapes

In [9]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [10]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


#### Tensor Data Types

In [11]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[18,  7, 19],
        [10,  2, 19]], dtype=torch.int32)


<b>Available data types:</b>
<ul>
    <li> torch.bool </li>
    <li> torch.int8 </li>
    <li> torch.uint8 </li>
    <li> torch.int16 </li>
    <li> torch.int32 </li>
    <li> torch.int64 </li>
    <li> torch.half </li>
    <li> torch.float </li>
    <li> torch.double </li>
    <li> torch.bfloat </li>
</ul>

#### Math and Logic with PyTorch Tensors

In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2)*2
threes = (torch.ones(2, 2)*7 - 1)/2
fours = twos**2
sqrt2s = twos**0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes*fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [14]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

#print(a*b) #throws a run time error intentionally, as sizes don't match

#### Tensor Broadcasting

In [15]:
rand = torch.rand(2, 4)
doubled = rand*(torch.ones(1, 4)*2)

print(rand)
print(doubled)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614]])
tensor([[1.2291, 1.1998, 1.0026, 1.8793],
        [1.7312, 1.0413, 1.3730, 0.7228]])


Here the tensors are of different size, yet they are still multiplied together. This is because the 1x4 tensor is multiplied by each row of the 2x4 tensor. Similarities in shape can allow for broadcasting, which is important when working with batches.

In [16]:
a = torch.ones(4, 3, 2)
b = a*torch.rand(  3, 2)
print(b)

c = a*torch.rand(  3, 1)
print(c)

d = a*torch.rand(  1, 2)
print(d)

tensor([[[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]]])
tensor([[[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]]])
tensor([[[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]]])


Broadcasting matches from last to first, so ```b = a*torch.rand(4,3)``` will not work.

#### More Math with tensors

In [17]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.9238, 0.5724, 0.0791, 0.2629],
        [0.1986, 0.4439, 0.6434, 0.4776]])
tensor([[-0., -0., 1., -0.],
        [-0., 1., 1., -0.]])
tensor([[-1., -1.,  0., -1.],
        [-1.,  0.,  0., -1.]])
tensor([[-0.5000, -0.5000,  0.0791, -0.2629],
        [-0.1986,  0.4439,  0.5000, -0.4776]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7375, 0.8328],
        [0.8444, 0.2941]])
tensor([[2.2125, 2.4985],
        [2.5332, 0.8822]])
torch.return_types.svd(
U=tensor([[-0.7889, -0.6145],
        [-0.6145,  0.7889]]),
S=tensor([4.1498, 1.0548]),
V=tensor([[-0.7957,  0.6056],
        [-0.6056, -0.7957]]))


#### Altering tensors in Place
When running binaray operations on tensors, a third new tensor will often be returned, occupying a new space in memory. Sometimes you may wish to alter a tensor in place, f.e. for element-wise computation where intermediate values can be discarded. To do this, the math functions have versions appended with an underscore (`_`).

In [18]:
a = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print(f"a: {a}")
print(torch.sin(a))
print(f"a: {a}\n")

b = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print(f"b: {b}")
print(torch.sin_(b))
print(f"b: {b}\n")

a: tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
a: tensor([0.0000, 0.7854, 1.5708, 2.3562])

b: tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
b: tensor([0.0000, 0.7071, 1.0000, 0.7071])



In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print(f"Before:\n{a}\n{b}\n")
print(f"After adding:\n{a.add_(b)}\n{a}\n{b}\n")
print(f"After multiplying:\n{b.mul_(b)}\n{b}\n")

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After adding:
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After multiplying:
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])



In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.rand(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c) #contents of c will have changed

assert c is d
assert id(c), old_id #same object

torch.rand(2, 2, out=c) #works for creation too
print(c)
assert id(c), old_id #still same object

tensor([[0.0776, 0.4004],
        [0.9877, 0.0352]])
tensor([[0.3653, 0.8699],
        [0.2364, 0.3604]])
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]])


#### Copying Tensors
Assigning a tensor to a variable makes the variable a label of the tensor, and will update with changes, as shown below. To copy, use the `clone()` method, which keeps autograd on if enabled on the original.

In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [22]:
c = torch.ones(2, 2)
d = c.clone()

assert d is not c
print(torch.eq(c, d))

c[0][1] = 561
print(d)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [23]:
e = torch.rand(2, 2, requires_grad=True)
print(e)

f = e.clone()
print(f)

g = e.detach().clone() #removes attatched history
print(g)

print(e)

tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], requires_grad=True)
tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], grad_fn=<CloneBackward0>)
tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]])
tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], requires_grad=True)


#### Moving to GPU
CUDA (Compute Unified Device Architecture) compatible GPUs allow for parallel computing using pytorch. To move from the CPU to the GPU, first checks need to be made to ensure it is available:

In [24]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only :(')

We have a GPU!


There are multiple ways to get the data onto the target device. This can be done at creation:

In [25]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


You can query the number of GPUs with the `torch.cuda.device_count()` function. If you have more than one GPU, you can specify them by index: `device='cuda:0'`, `device='cuda:1'` etc. 

The best way to handle this is to create a device handle that can be passed to your tensors, instead of a string.

In [26]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

Device: cuda


In [27]:
x = torch.rand(2, 2, device=my_device)
print(x)

tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


Existing tensors can be moved to another device by using the `to()` method.

In [28]:
y = torch.rand(2, 2)
y = y.to(my_device)
print(y)

tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]], device='cuda:0')


In [29]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
#z = x + y #throws an exception

#### Manipulating Tensor Shapes
One case where you may need to change the number of dimensions is passing a single instance of input to a model. Pytorch models expect bathes of input.

In [30]:
a = torch.rand(3, 226, 226) #random 3 colour 226*226 image
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The `unsqueeze()` function adds a dimension of extent 1. `squeeze()` can be used to reduce dimensions of extent 1. Using `squeeze()` on dimensions of size 2 will do nothing.

In [31]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)
print(c.squeeze())

tensor([[[[[0.4929]]]]])
tensor(0.4929)


In [32]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057, 0.9335,
         0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952,
         0.9176, 0.8960]])
torch.Size([20])
tensor([0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057, 0.9335,
        0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823, 0.8637, 0.1891, 0.3952,
        0.9176, 0.8960])
torch.Size([2, 2])
torch.Size([2, 2])


Another place `unsqueeze()` may be used is to ease broadcasting.

In [33]:
a = torch.ones(4, 3, 2)
c = a*torch.rand(  3, 1) #third dimension = 1, 2nd dim identical to a
print(c)

tensor([[[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]]])


In [34]:
a = torch.ones(4, 3, 2)
b = torch.rand(  3) #a*b will generate a run time error
c = b.unsqueeze(1)
print(c.shape)
print(a*c)

torch.Size([3, 1])
tensor([[[0.0438, 0.0438],
         [0.0636, 0.0636],
         [0.2884, 0.2884]],

        [[0.0438, 0.0438],
         [0.0636, 0.0636],
         [0.2884, 0.2884]],

        [[0.0438, 0.0438],
         [0.0636, 0.0636],
         [0.2884, 0.2884]],

        [[0.0438, 0.0438],
         [0.0636, 0.0636],
         [0.2884, 0.2884]]])


In [35]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


`reshape()` can also be used for larger changes. This returns a view on the tensor changed, so any changes made in the source tensor will be reflected in the view unless `clone()` is used.

In [36]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6*20*20)
print(input1d.shape)

print(torch.reshape(output3d, (6*20*20,)).shape) # , is needed as a tuple is expected

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


#### NumPy Bridge
Converting between numpy and PyTorch is very easy, as shown below. One key note is that the converted objects share the same underlying memory, so changes in one are reflected in the other, as shown in the bottom cell.

In [37]:
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [38]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1506, 0.5940, 0.6689],
        [0.0140, 0.3838, 0.0171]])
[[0.1506499  0.59399456 0.668864  ]
 [0.01402104 0.38376427 0.01713592]]


In [39]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[1.5064991e-01 5.9399456e-01 6.6886401e-01]
 [1.4021039e-02 1.7000000e+01 1.7135918e-02]]


<br>