# Pytorch Test Autograd
Notebook for testing pytorch automatic differentiation, using [Pytorch](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) website tutorial.<br>
[Main code](#Main-Code).

### Choices for data

<br>

### Libaries and Modules
Importing the necessary libaries and modules for the notebook.

In [1]:
#Import cell
import matplotlib.dates as mdates
import matplotlib as mpl 
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
import pickle as pk
import matplotlib.ticker as ticker
import torch

print("Imports complete")

Imports complete


<br>

### Importing data sets
Importing the data for the models.

In [2]:
#Importing data sets


<br>

### Classes
<b>Class List:</b><br>
<ul>
<li>
</ul>

In [3]:

print("Classes defined.")

Classes defined.


<br>

### Calculation functions
<b>Functions:</b><br>
<ul>
<li>
</ul>

In [4]:
#Calculation functions cell


print("Calculation functions defined.")

Calculation functions defined.


<br>

### Plotting functions
<b>Functions:</b>
<ul>
<li> 
</ul>

In [5]:
#Plotting functions Cell


print("Plotting functions defined.")

Plotting functions defined.


<br>

### Main Code

In [6]:
x = torch.ones(5) #input tensor
y= torch.zeros(3) #expected output
w = torch.randn(5,3, requires_grad=True) #optimise
b = torch.randn(3, requires_grad=True) #optimise
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [7]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000019489651C70>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000019489651B80>


In [8]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2800, 0.3150, 0.0165],
        [0.2800, 0.3150, 0.0165],
        [0.2800, 0.3150, 0.0165],
        [0.2800, 0.3150, 0.0165],
        [0.2800, 0.3150, 0.0165]])
tensor([0.2800, 0.3150, 0.0165])


In [9]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad(): #disables gradient tracking
    z = torch.matmul(x, w)+b 
    print(z.requires_grad)

True
False


In [10]:
z = torch.matmul(x, w)+b
z_det = z.detach() #disables gradient tracking
print(z_det.requires_grad) 

False


<br>

### Jacobian Products

In [11]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])


Note how backward being called a second time with the same arguements has a different gradient. This is due to pytorch accumlating the gradients. To computer properly, make sure to zero out grad before you do.

<br>

<br>