# Pytorch Test Youtube Introduction
Notebook for following along with the Pytorch introduction, using [Pytorch](https://pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html) website tutorial. This notebook will be similar to the previous Pytorch Test notebooks, as the [youtube content](https://youtu.be/IC0_FRiX-sw?t=231) covers similiar works.

### Choices for data

<br>

### Libaries and Modules
Importing the necessary libaries and modules for the notebook.

In [2]:
#Import cell
import matplotlib.dates as mdates
import matplotlib as mpl 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle as pk
import matplotlib.ticker as ticker
import torch


print("Imports complete")

Imports complete


<br>

### Importing data sets
Importing the data for the models.

<b>Import sample data set and corresponding time/geo data</b>

In [1]:
#Importing data sets

print("Data sets successfully imported.")

Data sets successfully imported.


<br>

### Class Definitions
<b>Classes:</b><br>
<ul>
<li>
</ul>

In [ ]:
#Class definition cell

print("Classes defined.")

<br>

### Calculation functions
<b>Functions:</b><br>
<ul>
<li>
</ul>

In [3]:
#Calculation functions cell


print("Calculation functions defined.")

Calculation functions defined.


<br>

### Plotting functions
<b>Functions:</b>
<ul>
<li> 
</ul>

In [4]:
#Plotting functions Cell


print("Plotting functions defined.")

Plotting functions defined.


<br>

### Main code

In [3]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [4]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


Often it is useful to initialize learning weights randomly, often with a specific seed for the PRNG for repeatability.

In [8]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print(f"A random tensor:\n{r1}\n")

r2 = torch.rand(2, 2)
print(f"A different random tensor:\n{r2}\n")

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print(f"A new tensor which should match r1:\n{r3}\n")

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

A new tensor which should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])



Arithmetic operations are performed intuitively. Operations with scalars are performed across the entire tensor.

In [9]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3)*2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
print("Running r1 + r2 will create a run time error")

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
Running r1 + r2 will create a run time error


In [11]:
r = (torch.rand(2, 2) - 0.5)*2 #values between -1 and 1
print(f"A random matrix, r:\n{r}\n")

print(f"Absolute value of r:\n{torch.abs(r)}\n")
print(f"Inverse sine of r:\n{torch.asin(r)}\n")
print(f"Determinant of r:{torch.det(r)}\n")
print(f"Singular value decomposition of r:\n{torch.svd(r)}\n")
print(f"Average and standard deviation of r:\n{torch.std_mean(r)}\n")
print(f"Maximum value of r:{torch.max(r)}")

A random matrix, r:
tensor([[-0.7231, -0.0482],
        [ 0.4961, -0.9278]])

Absolute value of r:
tensor([[0.7231, 0.0482],
        [0.4961, 0.9278]])

Inverse sine of r:
tensor([[-0.8083, -0.0482],
        [ 0.5191, -1.1884]])

Determinant of r:0.6947851777076721

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.4003,  0.9164],
        [ 0.9164,  0.4003]]),
S=tensor([1.1154, 0.6229]),
V=tensor([[ 0.6672, -0.7449],
        [-0.7449, -0.6672]]))

Average and standard deviation of r:
(tensor(0.6507), tensor(-0.3007))

Maximum value of r:0.49614179134368896


<br>